### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [DrafaKiller/Thread-dart#1]
When I use `Thread.Compute` method immediately when Flutter application starts, I faced this error
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      Thread.emit (package:thread/thread.dart:250:11)
<asynchronous suspension>
```
It has been thrown from their
```
245  /// Emits an event to be sent to the thread.
256  ///
247  /// If the thread is not alive, this will wait until it is.
248  Future<void> emit<T>(String type, [T? data]) async {
249    await untilAlive();
250    events!.emit(type, data);
251  }

```
It seems like that `events` take some time to be initialized. So I have delayed my code (2 seconds), and everything goes will.

Another thing, when I debugging the code I noted that there is an error in `start` method.
```
134    isolate = await Isolate.spawn(
135      debugName: 'ThreadIsolate-${uuid.v4()}',
136      _entryPoint,
137      ThreadInitialState(receivePort.sendPort, _eventHandler),
138    );
```
How keyword arguments `debugName` passed before positional arguments `entryPoint` and `message`?
This causes a compile-time error.

**Comment by DrafaKiller** [comment]
I couldn't replicate this issue, but I see how it could happen.
The `.untilAlive()` method was skipping itself even though the event emitter isn't initialized.

Even though I can't replicate it, I have reenforced it. Should be fixed in the latest version.

---

> How keyword arguments `debugName` passed before positional arguments `entryPoint` and `message`?
This causes a compile-time error.

This isn't a problem in the new Dart syntax, but I changed it anyway.
