### ISSUE TITLE
Strange Behaviour

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [DrafaKiller/Thread-dart#2]
I faced strange behavior with Thread.

This happened when I execute `async` function inside `compute` method and store the result in variable (The application stuck without throw any `Errors/Exceptions`), and If I put the `compute` method inside `print` function directly, it works pretty well.
```
    final thread = Thread.empty();

    print(await thread.compute(() => 1));            // ✓

    print(await thread.compute(() async => 2));      // ✓

    var res1 = await thread.compute(() => 1);        // ✓
    print(res1);

    var res2 = await thread.compute(() async => 2);  // <-- stuck here
    print(res2);
```

**Comment by DrafaKiller** [comment]
Seems like Dart might be handling the Future differently, but it works when using `final` instead of `var`, it really is strange 
behavior.

Either way, setting the result of the computation as `FutureOr` seems to force Dart to handle it correctly for both cases, it will be fixed in the latest version.

---

Thank you for reporting.
